### ISSUE TITLE
Just a help on rewriting docker compose for GDAL Only

### ISSUE THREAD

**Issue by haneefputtur** [zflamig/goes-to-cog#1]
Hi,

Will you be able to help to rewrite Docker file just to have below imports

import json
import boto3
import os
import numpy as np
import gdal 

In one of my project i only need this much.. 

Hope you are kind enough to help me out :)

Sorry this is not an issue, Help Request.

**Comment by zflamig** [comment]
Hi! Feel free to fork and use for your needs. But otherwise I'm not sure what you are asking or what the extra imports are currently

**Comment by haneefputtur** [comment]
Thanks for your quick reply. I was able to do it and appreciate your efforts.
